feat: updating workflows and tasks to latest varsion
defenseunicorns/uds-package-artifactory pull request #48
Opened 2024-10-29 19:33 UTC by Michael-Kruggel

2024-10-30 04:01 UTC, corang approved these changes

2024-10-30 18:05 UTC, mkborland approved these changes

2024-10-30 18:13 UTC, robmcelvenny requested changes
once change is made, LGTM

2024-10-30 18:13 UTC, robmcelvenny commented on .github/workflows/pull-request-conditionals.yaml
file not needed

2024-10-30 18:15 UTC, Michael-Kruggel commented
Deleted the file @robmcelvenny

2024-10-30 18:43 UTC, robmcelvenny submitted a review, later dismissed
LGTM

2024-11-01 19:34 UTC, corang approved these changes

2024-11-01 19:34 UTC, merged